CREATE DATABASE IF NOT EXISTS documentDB;

USE documentDB;

CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  path VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL
);
